apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: queue-server
  labels:
    app: postgres
data:
  POSTGRES_DB: 'ps_db'
  POSTGRES_USER: 'ps_user'
  POSTGRES_PASSWORD: 'SecurePassword'
  init.sql: |
    CREATE DATABASE IF NOT EXISTS queue_server;
    \c queue_server;

    CREATE TABLE IF NOT EXISTS queues (
        name VARCHAR(36) PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS messages (
        id VARCHAR(36) PRIMARY KEY,
        queue_name VARCHAR(36) NOT NULL REFERENCES queues(name) ON DELETE CASCADE,
        receipt_handle VARCHAR(36) UNIQUE NOT NULL,
        visibility_timeout TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        body TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO queues (name) VALUES ('queue');
