apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: queue-server
  labels:
    app: postgres
data:
  POSTGRES_DB: 'ps_db'
  POSTGRES_USER: 'ps_user'
  POSTGRES_PASSWORD: 'SecurePassword'
  init.sql: |
    CREATE DATABASE queue_server;
    \c queue_server;
    
    CREATE TABLE queues (
        name VARCHAR(36) PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE messages (
        id VARCHAR(36) PRIMARY KEY,
        queue_name VARCHAR(36) NOT NULL REFERENCES queues(name) ON DELETE CASCADE,
        body TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );