apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: queue-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:17'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-init-sql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              name: postgres-init-sql  # Mount the SQL script from ConfigMap
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: postgres-init-sql
          configMap:
            name: postgres-init-sql
