apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: queue-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest  # Nome da imagem que você vai buildar no Minikube
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: 'postgres'
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: 'ps_user'
        - name: POSTGRES_PASSWORD
          value: 'SecurePassword'
        - name: POSTGRES_DB_NAME
          value: 'queue_server'
        # command: ['sleep', '300'] // For tests