apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: queue-server
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
